services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  frontend:
      context: ./student-frontend
    build:
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"